---
# file: roles/htpc/tasks/main.yml

- name: remove_packages
  yum: name={{ item }} state=absent
  with_flattened:
    - packages_remove
  notify: yum_autoremove

- name: install_packages
  yum: name={{ item }} state=installed
  with_flattened:
    - packages_misc
    - packages_xapps
    - packages_xdeps
    - packages_drivers
  notify: yum_autoremove

- name: install_config_samba
  copy: src=smb.conf dest=/etc/samba/ owner=root mode=0644

- name: install_config_nvidia
  copy: src=20-nvidia.conf dest=/etc/X11/xorg.conf.d/ owner=root mode=0644

- name: install_config_lirc
  shell: rsync -ci /usr/share/lirc-remotes/mceusb/lircd.conf.mceusb /etc/lirc/lircd.conf
  register: rsync_result
  changed_when: "rsync_result.stdout != ''"

- name: install_kodi_service
  copy: src=kodi.service dest=/etc/systemd/system/ owner=root mode=0644

- name: enable_additional_services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - avahi-daemon
    - smb
    - nmb
    - lircd
    - kodi
