---
# file: roles/macbook/tasks/main.yml

- name: install_packages
  yum: name={{ item }} state=installed
  with_flattened:
    - packages_drivers
    - packages_misc
  notify: yum_autoremove

- name: install_config_blacklist_b43
  copy: src=blacklist.conf dest=/etc/modprobe.d/ owner=root mode=0644

- name: install_config_synaptics
  copy: src=60-synaptics.conf dest=/etc/X11/xorg.conf.d/ owner=root mode=0644

- name: disable_apple_remote
  copy: content='ACTION=="add", ATTR{idVendor}=="05ac", ATTR{idProduct}=="8242", RUN+="/bin/sh -c \'echo 0 >/sys$DEVPATH/authorized\'"' dest=/etc/udev/rules.d/99-disable-apple-ir.rules owner=root mode=0644

- name: disable_wifi_powersaving
  lineinfile: dest=/etc/default/tlp regexp='^WIFI_PWR_ON_BAT=.*' line='WIFI_PWR_ON_BAT=1'

- name: add_kernel_parameters
  lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=(?!.*i915.*)(.*)(rhgb.*)' line='GRUB_CMDLINE_LINUX=\g<1>i915.modeset=1 i915.enable_rc6=1 i915.enable_fbc=1 i915.lvds_downclock=1 i915.semaphores=1 hid_apple.fnmode=2 \g<2>' backrefs=yes
  notify:
    - update_initramfs
    - update_grub

- name: install_config_sensors_1
  copy: src=macbook.conf dest=/etc/sensors.d/ owner=root mode=0644

- name: install_config_sensors_2
  lineinfile: dest=/etc/sysconfig/lm_sensors line='HWMON_MODULES="coretemp"' create=yes owner=root mode=0644
