---
# file: roles/macbook/handlers/main.yml

- name: yum_autoremove
  command: yum autoremove -y

- name: update_initramfs
  command: dracut --force

- name: update_grub
  command: grub2-mkconfig -o /etc/grub2-efi.cfg
