---
# file: roles/common/tasks/main.yml

- name: enable_sudo_without_password
  replace: dest=/etc/sudoers regexp='^#\s*(%wheel\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL)' replace='\1'

- name: disable_sudo_with_password
  replace: dest=/etc/sudoers regexp='^\s*(%wheel\s+ALL=\(ALL\)\s+ALL)' replace='# \1'

- name: remove_packages
  yum: name={{ item }} state=absent
  with_flattened:
    - packages_remove

- name: install_additional_repositories
  copy: src={{ item }} dest=/etc/yum.repos.d/ owner=root mode=0644
  with_fileglob:
    - "*.repo"

- name: install_additional_repositories_keys
  rpm_key: state=present key={{ item }}
  with_items:
    - 6446D859                                                                                              # rpmfusion-free
    - A668B376                                                                                              # rpmfusion-nonfree
    - https://dl-ssl.google.com/linux/linux_signing_key.pub                                                 # google-chrome
    - https://d2t3ff60b2tol4.cloudfront.net/repomd.xml.key                                                  # insync
    - http://download.opensuse.org/repositories/home:/paolorotolo:/numix/Fedora_21/repodata/repomd.xml.key  # numix

- name: update_all_packages
  yum: name=* state=latest

- name: install_packages
  yum: name={{ item }} state=installed
  with_flattened:
    - packages_bootstrap
    - packages_misc
    - packages_devel
    - packages_codecs
    - packages_xapps
    - packages_numix

- name: install_user_rbenv
  git: repo=https://github.com/sstephenson/rbenv.git version=master dest=/home/edgard/.rbenv
  sudo_user: edgard

- name: install_user_rubybuild
  git: repo=https://github.com/sstephenson/ruby-build.git version=master dest=/home/edgard/.rbenv/plugins/ruby-build
  sudo_user: edgard

# - name: install_user_gnomeshell_extension_caffeine
#   git: repo=https://github.com/eonpatapon/gnome-shell-extension-caffeine.git version=master dest=/home/edgard/.local/share/gnome-shell/extensions/caffeine@patapon.info
#   sudo_user: edgard

- name: set_selinux_permissive
  replace: dest=/etc/sysconfig/selinux regexp='^(SELINUX=).*$' replace='\1permissive'

- name: optimize_disk_io_schedulers
  copy: src=60-io_schedulers.rules dest=/etc/udev/rules.d/ owner=root mode=0644

- name: optimize_font_rendering_1
  copy: src=local.conf dest=/etc/fonts/ owner=root mode=0644

- name: optimize_font_rendering_2
  copy: src=Xresources dest=/home/edgard/.Xresources owner=edgard mode=0664

- name: enable_additional_services
  service: name={{ item }} enabled=yes state=started
  with_items:
    - sshd
    - docker
    - ddclient
